In [2]:
from __future__ import print_function
import pandas as pd
import numpy as np
import seaborn as sns
import mysql.connector
from mysql.connector import errorcode
from datetime import date, datetime, timedelta

In [3]:
df1 = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_vegetaux_2014.csv", encoding="utf-8")
df2 = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_vegetaux_2015.csv", encoding="utf-8")
df3 = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_vegetaux_2016.csv", encoding="utf-8")
df4 = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_vegetaux_2017.csv", encoding="utf-8")
df5 = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_vegetaux_2018.csv", encoding="utf-8")

In [4]:
frames = [df1, df2, df3, df4, df5]
veg = pd.concat(frames)

In [5]:
ani = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_animaux.csv", encoding="utf-8")
cer = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_cereal_excl.csv", encoding="utf-8")
pop = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_population.csv", encoding="utf-8")
pop_sous_nut = pd.read_csv("C:\\Users\\Cyrille\\Documents\\FAO\\FAOSTAT_data_personnes_en_sous_nutrition.csv", encoding="utf-8")

In [6]:
ani["origin"] = "animal"
veg["origin"] = "vegetal"

In [7]:
temp = ani.append(veg)

In [8]:
temp.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole', 'origin'],
      dtype='object')

In [9]:
temp_test= temp.pivot_table(index=["Code zone", "Zone", "Code Produit", "Produit", "Année", "origin"], columns = ["Élément"], values = ["Valeur"], aggfunc=sum)

In [10]:
temp_test.head()

                                                                                  Valeur  \
Élément                                                      Alimentation pour touristes
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                         NaN
                                               2015  vegetal                         NaN
                                               2016  vegetal                         NaN
                                               2017  vegetal                         NaN
                                               2018  vegetal                         NaN

                                                                                    \
Élément                                                      Aliments pour animaux
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                 110.0
                                               2015  vegetal                 125.0
                                               2016  vegetal                 128.0
                                               2017  vegetal                 105.0
                                               2018  vegetal                 118.0

                                                                                                    \
Élément                                                      Autres utilisations (non alimentaire)
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                   0.0
                                               2015  vegetal                                   0.0
                                               2016  vegetal                                   0.0
                                               2017  vegetal                                   0.0
                                               2018  vegetal                                   0.0

                                                                                                             \
Élément                                                      Disponibilité alimentaire (Kcal/personne/jour)
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                         1107.0
                                               2015  vegetal                                         1109.0
                                               2016  vegetal                                         1164.0
                                               2017  vegetal                                         1154.0
                                               2018  vegetal                                         1151.0

                                                                                                                     \
Élément                                                      Disponibilité alimentaire en quantité (kg/personne/an)
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                             139.33
                                               2015  vegetal                                             139.66
                                               2016  vegetal                                             146.99
                                               2017  vegetal                                             145.43
                                               2018  vegetal                                             144.90

                                                                                                                            \
Élément                                                      Disponibilité de matière grasse en quantité (g/personne/jour)
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                               3.90
                                               2015  vegetal                                               4.02
                                               2016  vegetal                                               4.22
                                               2017  vegetal                                               4.28
                                               2018  vegetal                                               4.40

                                                                                                                       \
Élément                                                      Disponibilité de protéines en quantité (g/personne/jour)
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                              33.01
                                               2015  vegetal                                              33.07
                                               2016  vegetal                                              34.70
                                               2017  vegetal                                              34.36
                                               2018  vegetal                                              34.25

                                                                                       \
Élément                                                      Disponibilité intérieure
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                    639.0
                                               2015  vegetal                    748.0
                                               2016  vegetal                    650.0
                                               2017  vegetal                    547.0
                                               2018  vegetal                    571.0

                                                                                      \
Élément                                                      Exportations - Quantité
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                     1.0
                                               2015  vegetal                     2.0
                                               2016  vegetal                     1.0
                                               2017  vegetal                     1.0
                                               2018  vegetal                     1.0

                                                                                      \
Élément                                                      Importations - Quantité
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                   344.0
                                               2015  vegetal                   324.0
                                               2016  vegetal                   312.0
                                               2017  vegetal                   337.0
                                               2018  vegetal                   379.0

                                                                         \
Élément                                                      Nourriture
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal      406.0
                                               2015  vegetal      409.0
                                               2016  vegetal      432.0
                                               2017  vegetal      428.0
                                               2018  vegetal      428.0

                                                                     \
Élément                                                      Pertes
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal   30.0
                                               2015  vegetal   59.0
                                               2016  vegetal   64.0
                                               2017  vegetal   15.0
                                               2018  vegetal   16.0

                                                                         \
Élément                                                      Production
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal      338.0
                                               2015  vegetal      363.0
                                               2016  vegetal      350.0
                                               2017  vegetal      176.0
                                               2018  vegetal      187.0

                                                                               \
Élément                                                      Résidus Semences
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal    46.0     32.0
                                               2015  vegetal   106.0     33.0
                                               2016  vegetal   -22.0     33.0
                                               2017  vegetal   -42.0     25.0
                                               2018  vegetal   -27.0     20.0

                                                                         \
Élément                                                      Traitement
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal       16.0
                                               2015  vegetal       16.0
                                               2016  vegetal       17.0
                                               2017  vegetal       16.0
                                               2018  vegetal       16.0


Élément                                                      Variation de stock
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal               42.0
                                               2015  vegetal              -63.0
                                               2016  vegetal               11.0
                                               2017  vegetal              -34.0
                                               2018  vegetal               -5.0

In [11]:
temp_test.columns = ["Alimentation pour touristes", "Aliments pour animaux", "Autres utilisations (non alimentaire)", "Disponibilité alimentaire (Kcal/personne/jour)", "Disponibilité alimentaire en quantité (kg/personne/an)", "Disponibilité de matière grasse en quantité (g/personne/jour)", "Disponibilité de protéines en quantité (g/personne/jour)", "Disponibilité intérieure", "Exportations - Quantité", "Importations - Quantité","Nourriture", "Pertes", "Production", "Résidus", "Semences", "Traitement", "Variation de stock"]

In [12]:
temp_test.head()

                                                              Alimentation pour touristes  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                          NaN
                                               2015  vegetal                          NaN
                                               2016  vegetal                          NaN
                                               2017  vegetal                          NaN
                                               2018  vegetal                          NaN

                                                              Aliments pour animaux  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                  110.0
                                               2015  vegetal                  125.0
                                               2016  vegetal                  128.0
                                               2017  vegetal                  105.0
                                               2018  vegetal                  118.0

                                                              Autres utilisations (non alimentaire)  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                    0.0
                                               2015  vegetal                                    0.0
                                               2016  vegetal                                    0.0
                                               2017  vegetal                                    0.0
                                               2018  vegetal                                    0.0

                                                              Disponibilité alimentaire (Kcal/personne/jour)  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                          1107.0
                                               2015  vegetal                                          1109.0
                                               2016  vegetal                                          1164.0
                                               2017  vegetal                                          1154.0
                                               2018  vegetal                                          1151.0

                                                              Disponibilité alimentaire en quantité (kg/personne/an)  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                             139.33
                                               2015  vegetal                                             139.66
                                               2016  vegetal                                             146.99
                                               2017  vegetal                                             145.43
                                               2018  vegetal                                             144.90

                                                              Disponibilité de matière grasse en quantité (g/personne/jour)  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                               3.90
                                               2015  vegetal                                               4.02
                                               2016  vegetal                                               4.22
                                               2017  vegetal                                               4.28
                                               2018  vegetal                                               4.40

                                                              Disponibilité de protéines en quantité (g/personne/jour)  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                                              33.01
                                               2015  vegetal                                              33.07
                                               2016  vegetal                                              34.70
                                               2017  vegetal                                              34.36
                                               2018  vegetal                                              34.25

                                                              Disponibilité intérieure  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                     639.0
                                               2015  vegetal                     748.0
                                               2016  vegetal                     650.0
                                               2017  vegetal                     547.0
                                               2018  vegetal                     571.0

                                                              Exportations - Quantité  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                      1.0
                                               2015  vegetal                      2.0
                                               2016  vegetal                      1.0
                                               2017  vegetal                      1.0
                                               2018  vegetal                      1.0

                                                              Importations - Quantité  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                    344.0
                                               2015  vegetal                    324.0
                                               2016  vegetal                    312.0
                                               2017  vegetal                    337.0
                                               2018  vegetal                    379.0

                                                              Nourriture  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal       406.0
                                               2015  vegetal       409.0
                                               2016  vegetal       432.0
                                               2017  vegetal       428.0
                                               2018  vegetal       428.0

                                                              Pertes  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal    30.0
                                               2015  vegetal    59.0
                                               2016  vegetal    64.0
                                               2017  vegetal    15.0
                                               2018  vegetal    16.0

                                                              Production  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal       338.0
                                               2015  vegetal       363.0
                                               2016  vegetal       350.0
                                               2017  vegetal       176.0
                                               2018  vegetal       187.0

                                                              Résidus  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal     46.0
                                               2015  vegetal    106.0
                                               2016  vegetal    -22.0
                                               2017  vegetal    -42.0
                                               2018  vegetal    -27.0

                                                              Semences  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal      32.0
                                               2015  vegetal      33.0
                                               2016  vegetal      33.0
                                               2017  vegetal      25.0
                                               2018  vegetal      20.0

                                                              Traitement  \
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal        16.0
                                               2015  vegetal        16.0
                                               2016  vegetal        17.0
                                               2017  vegetal        16.0
                                               2018  vegetal        16.0

                                                              Variation de stock
Code zone Zone    Code Produit Produit         Année origin
1         Arménie 2511         Blé et produits 2014  vegetal                42.0
                                               2015  vegetal               -63.0
                                               2016  vegetal                11.0
                                               2017  vegetal               -34.0
                                               2018  vegetal                -5.0

In [13]:
data = temp_test.reset_index()

In [14]:
data.head()

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Résidus,Semences,Traitement,Variation de stock
0,1,Arménie,2511,Blé et produits,2014,vegetal,NaN,110.0,0.0,1107.0,...,639.0,1.0,344.0,406.0,30.0,338.0,46.0,32.0,16.0,42.0
1,1,Arménie,2511,Blé et produits,2015,vegetal,NaN,125.0,0.0,1109.0,...,748.0,2.0,324.0,409.0,59.0,363.0,106.0,33.0,16.0,-63.0
2,1,Arménie,2511,Blé et produits,2016,vegetal,NaN,128.0,0.0,1164.0,...,650.0,1.0,312.0,432.0,64.0,350.0,-22.0,33.0,17.0,11.0
3,1,Arménie,2511,Blé et produits,2017,vegetal,NaN,105.0,0.0,1154.0,...,547.0,1.0,337.0,428.0,15.0,176.0,-42.0,25.0,16.0,-34.0
4,1,Arménie,2511,Blé et produits,2018,vegetal,NaN,118.0,0.0,1151.0,...,571.0,1.0,379.0,428.0,16.0,187.0,-27.0,20.0,16.0,-5.0

In [15]:
data = data.fillna(-1)

In [16]:
pop_sous_nut = pop_sous_nut.fillna(-1)
pop_sous_nut.head(10)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,-1.0
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,8.9,F,Estimation FAO,-1.0
2,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,9.7,F,Estimation FAO,-1.0
3,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,10.5,F,Estimation FAO,-1.0
4,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20172019,2017-2019,millions,11.1,F,Estimation FAO,-1.0
5,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,2.5,F,Estimation FAO,-1.0
6,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,2.8,F,Estimation FAO,-1.0
7,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,3,F,Estimation FAO,-1.0
8,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,3.1,F,Estimation FAO,-1.0
9,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20172019,2017-2019,millions,3.3,F,Estimation FAO,-1.0

In [17]:
for index, row in pop_sous_nut.iterrows():
    if pop_sous_nut.loc[index, "Code année"] == 20132015:
        pop_sous_nut.loc[index, "Code année"] = 2014
        pop_sous_nut.loc[index, "Année"] = 2014
    if pop_sous_nut.loc[index, "Code année"] == 20142016:
        pop_sous_nut.loc[index, "Code année"] = 2015
        pop_sous_nut.loc[index, "Année"] = 2015
    if pop_sous_nut.loc[index, "Code année"] == 20152017:
        pop_sous_nut.loc[index, "Code année"] = 2016
        pop_sous_nut.loc[index, "Année"] = 2016
    if pop_sous_nut.loc[index, "Code année"] == 20162018:
        pop_sous_nut.loc[index, "Code année"] = 2017
        pop_sous_nut.loc[index, "Année"] = 2017
    if pop_sous_nut.loc[index, "Code année"] == 20172019:
        pop_sous_nut.loc[index, "Code année"] = 2018
        pop_sous_nut.loc[index, "Année"] = 2018
    if isinstance(pop_sous_nut.loc[index, "Valeur"], str) and pop_sous_nut.loc[index, "Valeur"].startswith('<') :
        pop_sous_nut.loc[index, "Valeur"] = 0.1
    pop_sous_nut.loc[index, "Unité"] = "1000 personnes"
    if pop_sous_nut.loc[index, "Valeur"] != -1 :
        pop_sous_nut.loc[index, "Valeur"] = 1000 * float(pop_sous_nut.loc[index, "Valeur"])

In [18]:
pop_sous_nut['Valeur'] = pop_sous_nut['Valeur'].astype(int)

In [19]:
pop = pop.fillna(-1)

In [22]:
DB_NAME = 'FAO_Project'

TABLES = {}
TABLES['population'] = (
    "CREATE TABLE `population` ("
    "  `Country` varchar(256) NOT NULL,"
    "  `Country_Code` SMALLINT NOT NULL,"
    "  `Year` SMALLINT NOT NULL,"
    "  `Population` int NOT NULL,"
    "  PRIMARY KEY (`Country`, `Year`)"
    ") ENGINE=InnoDB")

TABLES['dispo_alim'] = (
    "CREATE TABLE `dispo_alim` ("
    "  `pays` varchar(256) NOT NULL,"
    "  `code_pays` SMALLINT NOT NULL,"
    "  `année` SMALLINT NOT NULL,"
    "  `produit` varchar(256) NOT NULL,"
    "  `code_produit` SMALLINT NOT NULL,"
    "  `origin` varchar(256) NOT NULL,"
    "  `dispo_alim_tonnes` float,"
    "  `dispo_alim_kcal_p_j` float,"
    "  `dispo_prot` float,"
    "  `dispo_mat_gr` float,"
    "  PRIMARY KEY (`pays`, `année`, `produit`)"
    ") ENGINE=InnoDB")

TABLES['population_sous_nutrition'] = (
    "CREATE TABLE `population_sous_nutrition` ("
    "  `Country` varchar(256) NOT NULL,"
    "  `Country_Code` SMALLINT NOT NULL,"
    "  `Year` SMALLINT NOT NULL,"
    "  `Population` int NOT NULL,"
    "  PRIMARY KEY (`Country`, `Year`)"
    ") ENGINE=InnoDB")

TABLES['equilibre_prod'] = (
    "CREATE TABLE `equilibre_prod` ("
    "  `pays` varchar(256) NOT NULL,"
    "  `code_pays` SMALLINT NOT NULL,"
    "  `année` SMALLINT NOT NULL,"
    "  `produit` varchar(256) NOT NULL,"
    "  `code_produit` SMALLINT NOT NULL,"
    "  `origin` varchar(256) NOT NULL,"
    "  `dispo_int` float,"
    "  `alim_ani` float,"
    "  `semences` float,"
    "  `pertes` float,"
    "  `transfo` float,"
    "  `nourriture` float,"
    "  `autres_utilisations` float,"
    "  PRIMARY KEY (`pays`, `année`, `produit`)"
    ") ENGINE=InnoDB")

In [23]:
cnx = mysql.connector.connect(user='root', password='*Shekil602*!',
                              host='127.0.0.1')
cursor = cnx.cursor()

In [24]:
def create_database(cursor):
    try:
        cursor.execute(
            "CREATE DATABASE {} DEFAULT CHARACTER SET 'utf8'".format(DB_NAME))
    except mysql.connector.Error as err:
        print("Failed creating database: {}".format(err))
        exit(1)

In [25]:
try:
    cursor.execute("USE {}".format(DB_NAME))
except mysql.connector.Error as err:
    print("Database {} does not exists.".format(DB_NAME))
    if err.errno == errorcode.ER_BAD_DB_ERROR:
        create_database(cursor)
        print("Database {} created successfully.".format(DB_NAME))
        cnx.database = DB_NAME
    else:
        print(err)
        exit(1)

In [26]:
for table_name in TABLES:
    table_description = TABLES[table_name]
    try:
        print("Creating table {}: ".format(table_name), end='')
        cursor.execute(table_description)
    except mysql.connector.Error as err:
        if err.errno == errorcode.ER_TABLE_EXISTS_ERROR:
            print("already exists.")
        else:
            print(err.msg)
    else:
        print("OK")

cursor.close()
cnx.close()

Creating table population: OK
Creating table dispo_alim: OK
Creating table population_sous_nutrition: OK
Creating table equilibre_prod: OK

In [89]:
cnx = mysql.connector.connect(user='root', password='*Shekil602*!',
                              host='127.0.0.1',
                              database='FAO_Project')
cursor = cnx.cursor()

In [91]:
for index, row in pop.iterrows():
    country = row["Zone"]
    country_code = row["Code zone"]
    year = row["Année"]
    population = row["Valeur"]
    
    add_pop = ("INSERT INTO population "
               "(Country, Country_Code, Year, Population) "
               "VALUES (%s, %s, %s, %s)")
    data_pop = (country, country_code, year, population)
    
    cursor.execute(add_pop, data_pop)

for index, row in data.iterrows():
    
    pays = row["Zone"]
    code_pays = row["Code zone"]
    année = row["Année"]
    produit = row["Produit"]
    code_produit = row["Code Produit"]
    origin = row["origin"]
    dispo_alim_tonnes = row["Disponibilité alimentaire en quantité (kg/personne/an)"]
    dispo_alim_kcal_p_j = row["Disponibilité alimentaire (Kcal/personne/jour)"]
    dispo_prot = row["Disponibilité de protéines en quantité (g/personne/jour)"]
    dispo_mat_gr = row["Disponibilité de matière grasse en quantité (g/personne/jour)"]
    
    add_ani_veg = ("INSERT INTO  dispo_alim"
               "(pays, code_pays, année, produit, code_produit, origin, dispo_alim_tonnes, dispo_alim_kcal_p_j,dispo_prot, dispo_mat_gr) "
               "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)")
    data_ani_veg = (pays, code_pays, année, produit, code_produit, origin, dispo_alim_tonnes, dispo_alim_kcal_p_j,dispo_prot, dispo_mat_gr)
    
    cursor.execute(add_ani_veg, data_ani_veg)
    
for index, row in pop_sous_nut.iterrows():
    country = row["Zone"]
    country_code = row["Code zone"]
    year = row["Année"]
    population = row["Valeur"]
    
    add_pop_sous_nut = ("INSERT INTO population_sous_nutrition "
               "(Country, Country_Code, Year, Population) "
               "VALUES (%s, %s, %s, %s)")
    data_pop_sous_nut = (country, country_code, year, population)
    
    cursor.execute(add_pop_sous_nut, data_pop_sous_nut)
    
for index, row in data.iterrows():
    
    pays = row["Zone"]
    code_pays = row["Code zone"]
    année = row["Année"]
    produit = row["Produit"]
    code_produit = row["Code Produit"]
    origin = row["origin"]
    dispo_int = row["Disponibilité intérieure"]
    alim_ani = row["Aliments pour animaux"]
    semences = row["Semences"]
    pertes = row["Pertes"]
    transfo = row["Traitement"]
    nourriture = row["Nourriture"]
    autres_utilisations = row["Autres utilisations (non alimentaire)"]
    
    add_equ_prod = ("INSERT INTO equilibre_prod "
               "(pays, code_pays, année, produit, code_produit, origin, dispo_int, alim_ani, semences, pertes, transfo, nourriture, autres_utilisations) "
               "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)")
    
    data_equ_prod = (pays, code_pays, année, produit, code_produit, origin, dispo_int, alim_ani, semences, pertes, transfo, nourriture, autres_utilisations)
    
    cursor.execute(add_equ_prod, data_equ_prod)
    
cnx.commit()

AttributeError: 'tuple' object has no attribute 'iterrows'

In [38]:
#QUESTION 1

In [39]:
pop_totale = pop.groupby("Année")["Valeur"].sum()
for totale in pop_totale:
    #print("Population mondiale en {} : {} milliers de personnes".format(year, pop_totale[year]))
    #print("Population mondiale en {0} : {1} milliers de personnes".format(totale["Année"], pop_totale[year]))
    print(totale)
pop_totale

8562156
8650969
8739098
8826424
8912511

Année
2014    8562156
2015    8650969
2016    8739098
2017    8826424
2018    8912511
Name: Valeur, dtype: int64

In [40]:
#QUESTION 2 P1

In [41]:
#colonnes = ['Produit','Code Produit']

#distinct = cer['Code Produit'].unique()
#print(data.groupby('Produit'))
#print(cer.loc[cer['Code Produit'].isin(distinct),colonnes])
#print(distinct)

df_dist = cer.drop_duplicates(['Produit','Code Produit'])
print (df_dist.loc[:,['Code Produit','Produit'] ])

    Code Produit             Produit
0           2511     Blé et produits
5           2805     Riz et produits
10          2513    Orge et produits
15          2514    Maïs et produits
20          2515  Seigle et produits
25          2516              Avoine
30          2517  Millet et produits
35          2518  Sorgho et produits
37          2520    Céréales, Autres

In [42]:
data.loc[data['Code Produit'].isin(cer['Code Produit'].unique())]

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Résidus,Semences,Traitement,Variation de stock
0,1,Arménie,2511,Blé et produits,2014,vegetal,-1.0,110.0,0.0,1107.0,...,639.0,1.0,344.0,406.0,30.0,338.0,46.0,32.0,16.0,42.0
1,1,Arménie,2511,Blé et produits,2015,vegetal,-1.0,125.0,0.0,1109.0,...,748.0,2.0,324.0,409.0,59.0,363.0,106.0,33.0,16.0,-63.0
2,1,Arménie,2511,Blé et produits,2016,vegetal,-1.0,128.0,0.0,1164.0,...,650.0,1.0,312.0,432.0,64.0,350.0,-22.0,33.0,17.0,11.0
3,1,Arménie,2511,Blé et produits,2017,vegetal,-1.0,105.0,0.0,1154.0,...,547.0,1.0,337.0,428.0,15.0,176.0,-42.0,25.0,16.0,-34.0
4,1,Arménie,2511,Blé et produits,2018,vegetal,-1.0,118.0,0.0,1151.0,...,571.0,1.0,379.0,428.0,16.0,187.0,-27.0,20.0,16.0,-5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81897,351,Chine,2805,Riz et produits,2014,vegetal,10.0,13500.0,1717.0,795.0,...,197563.0,604.0,4540.0,165989.0,8216.0,208240.0,0.0,6955.0,1176.0,14613.0
81898,351,Chine,2805,Riz et produits,2015,vegetal,9.0,15023.0,2706.0,796.0,...,201165.0,494.0,5721.0,166834.0,8515.0,213724.0,0.0,6953.0,1125.0,17786.0
81899,351,Chine,2805,Riz et produits,2016,vegetal,9.0,13443.0,1183.0,805.0,...,202327.0,831.0,5987.0,169334.0,10344.0,212682.0,0.0,6939.0,1075.0,15511.0
81900,351,Chine,2805,Riz et produits,2017,vegetal,9.0,14061.0,2497.0,797.0,...,203535.0,1793.0,6661.0,168470.0,10423.0,214430.0,0.0,7018.0,1058.0,15763.0
81901,351,Chine,2805,Riz et produits,2018,vegetal,9.0,15159.0,2703.0,813.0,...,206919.0,3178.0,5221.0,172626.0,8624.0,214079.0,0.0,6875.0,924.0,9202.0

In [44]:
df= data.copy()
df['is_cereal']=np.where(data['Code Produit'].isin(cer['Code Produit'].unique()), True, False)

df

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Résidus,Semences,Traitement,Variation de stock,is_cereal
0,1,Arménie,2511,Blé et produits,2014,vegetal,-1.0,110.0,0.0,1107.0,...,1.0,344.0,406.0,30.0,338.0,46.0,32.0,16.0,42.0,True
1,1,Arménie,2511,Blé et produits,2015,vegetal,-1.0,125.0,0.0,1109.0,...,2.0,324.0,409.0,59.0,363.0,106.0,33.0,16.0,-63.0,True
2,1,Arménie,2511,Blé et produits,2016,vegetal,-1.0,128.0,0.0,1164.0,...,1.0,312.0,432.0,64.0,350.0,-22.0,33.0,17.0,11.0,True
3,1,Arménie,2511,Blé et produits,2017,vegetal,-1.0,105.0,0.0,1154.0,...,1.0,337.0,428.0,15.0,176.0,-42.0,25.0,16.0,-34.0,True
4,1,Arménie,2511,Blé et produits,2018,vegetal,-1.0,118.0,0.0,1151.0,...,1.0,379.0,428.0,16.0,187.0,-27.0,20.0,16.0,-5.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81907,351,Chine,2899,Miscellanees,2014,vegetal,5.0,-1.0,0.0,0.0,...,1748.0,690.0,224.0,-1.0,-1.0,-1292.0,-1.0,-1.0,4.0,False
81908,351,Chine,2899,Miscellanees,2015,vegetal,6.0,-1.0,0.0,0.0,...,1842.0,749.0,230.0,-1.0,-1.0,-1356.0,-1.0,-1.0,28.0,False
81909,351,Chine,2899,Miscellanees,2016,vegetal,7.0,-1.0,0.0,0.0,...,1867.0,812.0,218.0,-1.0,-1.0,-1335.0,-1.0,-1.0,55.0,False
81910,351,Chine,2899,Miscellanees,2017,vegetal,7.0,-1.0,0.0,0.0,...,2097.0,890.0,207.0,-1.0,-1.0,-1481.0,-1.0,-1.0,60.0,False
81911,351,Chine,2899,Miscellanees,2018,vegetal,7.0,-1.0,0.0,0.0,...,2274.0,965.0,191.0,-1.0,-1.0,-1562.0,-1.0,-1.0,55.0,False

In [45]:
#QUESTION 2 P2

In [46]:
somme_t= sum(df['Alimentation pour touristes']!=-1)+sum(df['Aliments pour animaux']!=-1)

somme_a = sum(df['Aliments pour animaux']!=-1)

proportion= 100*somme_a/somme_t

print(proportion)

58.349779428836776

In [23]:
# Question 2.2.1: disponibilité alimentaire
df1 = data.copy()
df2 = pop.copy()
df1["food_supply_kcal"] = df1["Disponibilité alimentaire (Kcal/personne/jour)"] * df2["Valeur"] * 365
df1["food_supply_kgprot"] = df1["Disponibilité de protéines en quantité (g/personne/jour)"] * 0.001 * df2["Valeur"] * 365
df1

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Importations - Quantité,Nourriture,Pertes,Production,Résidus,Semences,Traitement,Variation de stock,food_supply_kcal,food_supply_kgprot
0,1,Arménie,2511,Blé et produits,2014,vegetal,-1.0,110.0,0.0,1107.0,...,344.0,406.0,30.0,338.0,46.0,32.0,16.0,42.0,1.348372e+10,402075.49915
1,1,Arménie,2511,Blé et produits,2015,vegetal,-1.0,125.0,0.0,1109.0,...,324.0,409.0,59.0,363.0,106.0,33.0,16.0,-63.0,1.393027e+10,415395.90770
2,1,Arménie,2511,Blé et produits,2016,vegetal,-1.0,128.0,0.0,1164.0,...,312.0,432.0,64.0,350.0,-22.0,33.0,17.0,11.0,1.503282e+10,448143.38650
3,1,Arménie,2511,Blé et produits,2017,vegetal,-1.0,105.0,0.0,1154.0,...,337.0,428.0,15.0,176.0,-42.0,25.0,16.0,-34.0,1.528824e+10,455202.65440
4,1,Arménie,2511,Blé et produits,2018,vegetal,-1.0,118.0,0.0,1151.0,...,379.0,428.0,16.0,187.0,-27.0,20.0,16.0,-5.0,1.561651e+10,464696.46500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81907,351,Chine,2899,Miscellanees,2014,vegetal,5.0,-1.0,0.0,0.0,...,690.0,224.0,-1.0,-1.0,-1292.0,-1.0,-1.0,4.0,NaN,NaN
81908,351,Chine,2899,Miscellanees,2015,vegetal,6.0,-1.0,0.0,0.0,...,749.0,230.0,-1.0,-1.0,-1356.0,-1.0,-1.0,28.0,NaN,NaN
81909,351,Chine,2899,Miscellanees,2016,vegetal,7.0,-1.0,0.0,0.0,...,812.0,218.0,-1.0,-1.0,-1335.0,-1.0,-1.0,55.0,NaN,NaN
81910,351,Chine,2899,Miscellanees,2017,vegetal,7.0,-1.0,0.0,0.0,...,890.0,207.0,-1.0,-1.0,-1481.0,-1.0,-1.0,60.0,NaN,NaN
81911,351,Chine,2899,Miscellanees,2018,vegetal,7.0,-1.0,0.0,0.0,...,965.0,191.0,-1.0,-1.0,-1562.0,-1.0,-1.0,55.0,NaN,NaN

In [24]:
#Citez 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids ?  
mask=data["Disponibilité alimentaire en quantité (kg/personne/an)"]!=0
df1.loc[mask, 'ratio_kcal/kg']= df1.loc[mask, "food_supply_kgprot"]/df1.loc[mask,"Disponibilité alimentaire en quantité (kg/personne/an)"]
df1

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Nourriture,Pertes,Production,Résidus,Semences,Traitement,Variation de stock,food_supply_kcal,food_supply_kgprot,ratio_kcal/kg
0,1,Arménie,2511,Blé et produits,2014,vegetal,-1.0,110.0,0.0,1107.0,...,406.0,30.0,338.0,46.0,32.0,16.0,42.0,1.348372e+10,402075.49915,2885.778362
1,1,Arménie,2511,Blé et produits,2015,vegetal,-1.0,125.0,0.0,1109.0,...,409.0,59.0,363.0,106.0,33.0,16.0,-63.0,1.393027e+10,415395.90770,2974.337016
2,1,Arménie,2511,Blé et produits,2016,vegetal,-1.0,128.0,0.0,1164.0,...,432.0,64.0,350.0,-22.0,33.0,17.0,11.0,1.503282e+10,448143.38650,3048.801867
3,1,Arménie,2511,Blé et produits,2017,vegetal,-1.0,105.0,0.0,1154.0,...,428.0,15.0,176.0,-42.0,25.0,16.0,-34.0,1.528824e+10,455202.65440,3130.046444
4,1,Arménie,2511,Blé et produits,2018,vegetal,-1.0,118.0,0.0,1151.0,...,428.0,16.0,187.0,-27.0,20.0,16.0,-5.0,1.561651e+10,464696.46500,3207.014941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81907,351,Chine,2899,Miscellanees,2014,vegetal,5.0,-1.0,0.0,0.0,...,224.0,-1.0,-1.0,-1292.0,-1.0,-1.0,4.0,NaN,NaN,NaN
81908,351,Chine,2899,Miscellanees,2015,vegetal,6.0,-1.0,0.0,0.0,...,230.0,-1.0,-1.0,-1356.0,-1.0,-1.0,28.0,NaN,NaN,NaN
81909,351,Chine,2899,Miscellanees,2016,vegetal,7.0,-1.0,0.0,0.0,...,218.0,-1.0,-1.0,-1335.0,-1.0,-1.0,55.0,NaN,NaN,NaN
81910,351,Chine,2899,Miscellanees,2017,vegetal,7.0,-1.0,0.0,0.0,...,207.0,-1.0,-1.0,-1481.0,-1.0,-1.0,60.0,NaN,NaN,NaN
81911,351,Chine,2899,Miscellanees,2018,vegetal,7.0,-1.0,0.0,0.0,...,191.0,-1.0,-1.0,-1562.0,-1.0,-1.0,55.0,NaN,NaN,NaN

In [25]:
#Question 2.2.2:

df1["ratio_energie_kcal/kg"] = df1["ratio_kcal/kg"] / df1["food_supply_kcal"]
df1["ratio_energie_kcal/kg/personne/jour"] = df1["Nourriture"] / df1["ratio_energie_kcal/kg"] / df2["Valeur"] / 365

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Résidus,Semences,Traitement,Variation de stock,food_supply_kcal,food_supply_kgprot,ratio_kcal/kg,ratio_energie_kcal/kg,ratio_energie_kcal/kg/personne/jour,food_prot%
0,1,Arménie,2511,Blé et produits,2014,vegetal,-1.0,110.0,0.0,1107.0,...,46.0,32.0,16.0,42.0,1.348372e+10,402075.49915,2885.778362,2.140195e-07,155.743769,2885.778362
1,1,Arménie,2511,Blé et produits,2015,vegetal,-1.0,125.0,0.0,1109.0,...,106.0,33.0,16.0,-63.0,1.393027e+10,415395.90770,2974.337016,2.135161e-07,152.498186,2974.337016
2,1,Arménie,2511,Blé et produits,2016,vegetal,-1.0,128.0,0.0,1164.0,...,-22.0,33.0,17.0,11.0,1.503282e+10,448143.38650,3048.801867,2.028097e-07,164.932987,3048.801867
3,1,Arménie,2511,Blé et produits,2017,vegetal,-1.0,105.0,0.0,1154.0,...,-42.0,25.0,16.0,-34.0,1.528824e+10,455202.65440,3130.046444,2.047356e-07,157.797020,3130.046444
4,1,Arménie,2511,Blé et produits,2018,vegetal,-1.0,118.0,0.0,1151.0,...,-27.0,20.0,16.0,-5.0,1.561651e+10,464696.46500,3207.014941,2.053605e-07,153.609512,3207.014941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81907,351,Chine,2899,Miscellanees,2014,vegetal,5.0,-1.0,0.0,0.0,...,-1292.0,-1.0,-1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
81908,351,Chine,2899,Miscellanees,2015,vegetal,6.0,-1.0,0.0,0.0,...,-1356.0,-1.0,-1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN
81909,351,Chine,2899,Miscellanees,2016,vegetal,7.0,-1.0,0.0,0.0,...,-1335.0,-1.0,-1.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN
81910,351,Chine,2899,Miscellanees,2017,vegetal,7.0,-1.0,0.0,0.0,...,-1481.0,-1.0,-1.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN
81911,351,Chine,2899,Miscellanees,2018,vegetal,7.0,-1.0,0.0,0.0,...,-1562.0,-1.0,-1.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Question 2.2.3 % de protéines de chaque produit

In [47]:
df1["food_prot%"] = df1["food_supply_kgprot"] / df1["Disponibilité alimentaire en quantité (kg/personne/an)"]
df1

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Traitement,Variation de stock,food_supply_kcal,food_supply_kgprot,ratio_kcal/kg,ratio_energie_kcal/kg,ratio_energie_kcal/kg/personne/jour,food_prot%,dispo_nourriture_kg,protein%
0,1,Arménie,2511,Blé et produits,2014,vegetal,-1.0,110.0,0.0,1107.0,...,16.0,42.0,1.348372e+10,402075.49915,33.211132,2.140195e-07,155.743769,2885.778362,406000000.0,0.099033
1,1,Arménie,2511,Blé et produits,2015,vegetal,-1.0,125.0,0.0,1109.0,...,16.0,-63.0,1.393027e+10,415395.90770,34.059342,2.135161e-07,152.498186,2974.337016,409000000.0,0.101564
2,1,Arménie,2511,Blé et produits,2016,vegetal,-1.0,128.0,0.0,1164.0,...,17.0,11.0,1.503282e+10,448143.38650,34.798198,2.028097e-07,164.932987,3048.801867,432000000.0,0.103737
3,1,Arménie,2511,Blé et produits,2017,vegetal,-1.0,105.0,0.0,1154.0,...,16.0,-34.0,1.528824e+10,455202.65440,35.720183,2.047356e-07,157.797020,3130.046444,428000000.0,0.106356
4,1,Arménie,2511,Blé et produits,2018,vegetal,-1.0,118.0,0.0,1151.0,...,16.0,-5.0,1.561651e+10,464696.46500,36.487184,2.053605e-07,153.609512,3207.014941,428000000.0,0.108574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81907,351,Chine,2899,Miscellanees,2014,vegetal,5.0,-1.0,0.0,0.0,...,-1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,224000000.0,NaN
81908,351,Chine,2899,Miscellanees,2015,vegetal,6.0,-1.0,0.0,0.0,...,-1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,230000000.0,NaN
81909,351,Chine,2899,Miscellanees,2016,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,218000000.0,NaN
81910,351,Chine,2899,Miscellanees,2017,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,207000000.0,NaN
81911,351,Chine,2899,Miscellanees,2018,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,191000000.0,NaN

In [48]:
mask=data["Disponibilité alimentaire en quantité (kg/personne/an)"]!=0
df1.loc[mask, 'ratio_kcal/kg']= df1.loc[mask, "food_supply_kgprot"]/df1.loc[mask,"Disponibilité alimentaire en quantité (kg/personne/an)"]

df1

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Traitement,Variation de stock,food_supply_kcal,food_supply_kgprot,ratio_kcal/kg,ratio_energie_kcal/kg,ratio_energie_kcal/kg/personne/jour,food_prot%,dispo_nourriture_kg,protein%
0,1,Arménie,2511,Blé et produits,2014,vegetal,-1.0,110.0,0.0,1107.0,...,16.0,42.0,1.348372e+10,402075.49915,2885.778362,2.140195e-07,155.743769,2885.778362,406000000.0,0.099033
1,1,Arménie,2511,Blé et produits,2015,vegetal,-1.0,125.0,0.0,1109.0,...,16.0,-63.0,1.393027e+10,415395.90770,2974.337016,2.135161e-07,152.498186,2974.337016,409000000.0,0.101564
2,1,Arménie,2511,Blé et produits,2016,vegetal,-1.0,128.0,0.0,1164.0,...,17.0,11.0,1.503282e+10,448143.38650,3048.801867,2.028097e-07,164.932987,3048.801867,432000000.0,0.103737
3,1,Arménie,2511,Blé et produits,2017,vegetal,-1.0,105.0,0.0,1154.0,...,16.0,-34.0,1.528824e+10,455202.65440,3130.046444,2.047356e-07,157.797020,3130.046444,428000000.0,0.106356
4,1,Arménie,2511,Blé et produits,2018,vegetal,-1.0,118.0,0.0,1151.0,...,16.0,-5.0,1.561651e+10,464696.46500,3207.014941,2.053605e-07,153.609512,3207.014941,428000000.0,0.108574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81907,351,Chine,2899,Miscellanees,2014,vegetal,5.0,-1.0,0.0,0.0,...,-1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,224000000.0,NaN
81908,351,Chine,2899,Miscellanees,2015,vegetal,6.0,-1.0,0.0,0.0,...,-1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,230000000.0,NaN
81909,351,Chine,2899,Miscellanees,2016,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,218000000.0,NaN
81910,351,Chine,2899,Miscellanees,2017,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,207000000.0,NaN
81911,351,Chine,2899,Miscellanees,2018,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,191000000.0,NaN

In [27]:
df1["dispo_nourriture_kg"] = df1["Nourriture"] * 1000000
mask = df1["dispo_nourriture_kg"] !=0
df1.loc[mask, "ratio_kcal/kg"] = df1.loc[mask, "food_supply_kcal"] / df1.loc[mask, "dispo_nourriture_kg"] 
df1.loc[mask, "protein%"] = 100 * df1.loc[mask, "food_supply_kgprot"] / df1.loc[mask, "dispo_nourriture_kg"]
df1

,Code zone,Zone,Code Produit,Produit,Année,origin,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),...,Traitement,Variation de stock,food_supply_kcal,food_supply_kgprot,ratio_kcal/kg,ratio_energie_kcal/kg,ratio_energie_kcal/kg/personne/jour,food_prot%,dispo_nourriture_kg,protein%
0,1,Arménie,2511,Blé et produits,2014,vegetal,-1.0,110.0,0.0,1107.0,...,16.0,42.0,1.348372e+10,402075.49915,33.211132,2.140195e-07,155.743769,2885.778362,406000000.0,0.099033
1,1,Arménie,2511,Blé et produits,2015,vegetal,-1.0,125.0,0.0,1109.0,...,16.0,-63.0,1.393027e+10,415395.90770,34.059342,2.135161e-07,152.498186,2974.337016,409000000.0,0.101564
2,1,Arménie,2511,Blé et produits,2016,vegetal,-1.0,128.0,0.0,1164.0,...,17.0,11.0,1.503282e+10,448143.38650,34.798198,2.028097e-07,164.932987,3048.801867,432000000.0,0.103737
3,1,Arménie,2511,Blé et produits,2017,vegetal,-1.0,105.0,0.0,1154.0,...,16.0,-34.0,1.528824e+10,455202.65440,35.720183,2.047356e-07,157.797020,3130.046444,428000000.0,0.106356
4,1,Arménie,2511,Blé et produits,2018,vegetal,-1.0,118.0,0.0,1151.0,...,16.0,-5.0,1.561651e+10,464696.46500,36.487184,2.053605e-07,153.609512,3207.014941,428000000.0,0.108574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81907,351,Chine,2899,Miscellanees,2014,vegetal,5.0,-1.0,0.0,0.0,...,-1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,224000000.0,NaN
81908,351,Chine,2899,Miscellanees,2015,vegetal,6.0,-1.0,0.0,0.0,...,-1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,230000000.0,NaN
81909,351,Chine,2899,Miscellanees,2016,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,218000000.0,NaN
81910,351,Chine,2899,Miscellanees,2017,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,207000000.0,NaN
81911,351,Chine,2899,Miscellanees,2018,vegetal,7.0,-1.0,0.0,0.0,...,-1.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,191000000.0,NaN

In [49]:
#PRODUIT LES PLUS CALORIQUES
ratio = df1.groupby(['Produit', 'Année'])['ratio_kcal/kg'].mean()
prot = df1.groupby(['Produit', 'Année'])['protein%'].mean()
info_prod = pd.DataFrame({"ratio_kcal/kg": ratio, 'protein%': prot })
info_prod.sort_values("ratio_kcal/kg", ascending = False )[:20]

                                 ratio_kcal/kg  protein%
Produit                   Année
Feve de Cacao et produits 2017    73603.798485  2.428925
Palmistes                 2018    72790.855000  7.279085
                          2017    71286.325000  7.128633
Feve de Cacao et produits 2016    62647.765714  1.754137
                          2015    53399.500000  1.708784
                          2018    50759.544388  2.487218
Graines de coton          2018    38094.867500  3.809487
                          2017    37739.357500  3.773936
Graisses Animales Crue    2018    27130.756194  0.957949
                          2017    26673.896867  0.947184
Sucre, betterave          2016    24806.677500  2.480668
                          2015    24528.000000  2.452800
Girofles                  2016    24429.815000  2.442982
                          2015    24370.685000  2.437069
                          2014    24302.430000  2.430243
Sucre, betterave          2014    24243.117500  2.424312
Arachides Decortiquees    2016    22812.187984  0.095901
Café et produits          2016    21496.821607  0.705487
                          2015    21323.691449  0.735667
Arachides Decortiquees    2015    18695.594028  0.092364

In [29]:
#les plus protéinés 
info_prod.sort_values("protein%", ascending = False)[:20]

                                 ratio_kcal/kg  protein%
Produit                   Année
Palmistes                 2018       72.790855  7.279085
                          2017       71.286325  7.128633
Graines de coton          2018       38.094867  3.809487
                          2017       37.739357  3.773936
Feve de Cacao et produits 2018     2116.781000  2.487218
Sucre, betterave          2016       24.806677  2.480668
                          2015       24.528000  2.452800
Girofles                  2016       24.429815  2.442982
                          2015       24.370685  2.437069
                          2014       24.302430  2.430243
Feve de Cacao et produits 2017     2006.503550  2.428925
Sucre, betterave          2014       24.243118  2.424312
Feve de Cacao et produits 2016     1435.203360  1.754137
                          2015     1436.932000  1.708784
Racines nda               2016       13.150585  1.315058
                          2015       12.987065  1.298706
Patates douces            2017       12.480080  1.248008
Palmistes                 2016       11.853740  1.185374
                          2015       11.665400  1.166540
                          2014       11.476330  1.147633

In [31]:
#Question 3.1: Table sous nutrition
pop_1 = pop_sous_nut.copy()
pop_2 = pop.copy()

psn = pop_1.groupby("Année")["Valeur"].sum()
pm = pop_2.groupby("Année")["Valeur"].sum() * 1000000
#pop_2.groupby("Année")["Valeur"].sum() * pop_1.groupby("Année")["Valeur"].sum() / 100
#print(psn)
#print(pm)
#psn / pm
#pop_totale = pop_2.groupby("Année")["Valeur"].sum()
#for totale in pop_totale:
#    print("Population mondiale en {} : {} milliers de personnes".format(year, pop_totale[year]))
#pop_1.groupby("Année")["Valeur"].sum() * 100 / pop_2.groupby("Année")["Valeur"].sum()

In [50]:
#Question 3.2: Liste pays sous nutrition
#df_nutri = pop_sous_nutri.copy()
#df_nutri.loc[["Zone", "Valeur", "Année"]]
#liste_pays = df_nutri.groupby(["Zone","Valeur"]),["Année"]
#sous_nutri = pd.DataFrame(liste_pays)
#sous_nutri.sort_values("Valeur", ascending = False)[:20]
#df_nutri.sort_values(by=["Valeur"])[:20]

df_nutri = pop_sous_nut[['Zone', 'Année', 'Valeur']]


df_nutri.sort_values("Valeur", ascending = False)[:20]

           Zone Année  Valeur
425        Inde  2014  198300
426        Inde  2015  193100
427        Inde  2016  190900
428        Inde  2017  190100
429        Inde  2018  189200
685    Pakistan  2014   28500
689    Pakistan  2018   26100
686    Pakistan  2015   25400
688    Pakistan  2017   24800
649     Nigéria  2018   24600
687    Pakistan  2016   24600
310    Éthiopie  2014   24300
434   Indonésie  2018   24100
432   Indonésie  2016   24000
431   Indonésie  2015   24000
430   Indonésie  2014   23600
433   Indonésie  2017   23600
81   Bangladesh  2015   23300
648     Nigéria  2017   22800
80   Bangladesh  2014   22400

In [36]:
#Question 3.3 triez sur les pays les plus en sous nutri
exp = data.copy()
export = exp.groupby(["Zone","Produit"])
print(export)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001C4BD88CF48>